apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lq47
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-lq47@sha256:8bf77fabbfe161e60c084d07dd1c71c5afc6f8b27dbc9cecf308d91ed5bac511
        name: my-nodejs
        resources: {}
status: {}
